# podcasts:
late-night-linux: 'https://latenightlinux.com/feed/ogg'
ubuntu: 'http://feed.ubuntupodcast.org/ogg/'
revisionist-history: 'https://feeds.feedburner.com/RevisionistHistory'
changelog: 'https://changelog.com/podcast/feed'
tech-done-right: 'http://www.techdoneright.io/rss'
greater-than-code: 'https://www.greaterthancode.com/feed/podcast'
agile-uprising: 'http://agileuprising.libsyn.com/rss'
ill-drink-to-that: 'http://illdrinktothatpod.libsyn.com/rss'
radiolab: 'http://feeds.wnyc.org/radiolab'
